#!/bin/bash
# sudo su
#
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
# node con yum
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
# . ~/.nvm/nvm.sh
# Instalamos node
# nvm install node

# node con yum
yum install -y nodejs
# Instalamos angular 
# npm install -g @angular
