#!/bin/bash
# sudo su
apt install -y curl
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
# node con yum
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
# . ~/.nvm/nvm.sh
# Instalamos node
# nvm install node
apt install -y nodejs
# node con yum
# yum install -y nodejs
# Instalamos angular 
# npm install -g @angular
apt install -y npm
# Intalar dependencias
npm install
echo